package Clases;
// Generated 15/10/2015 02:12:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import java.util.Vector;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer idUsuarios;
     private String nombres;
     private String apellidos;
     private long telefono;
     private String correo;
     private String direccion;
     private String tipoUsuario;
     private String user;
     private String pass;
     private String estado;
     private Set seguimientoses = new HashSet(0);
     private Set contratoses = new HashSet(0);

     public Vector arrayToVector(){
        Vector lista = new Vector();
        lista.add(this.idUsuarios);
        lista.add(this.nombres);
        lista.add(this.apellidos);
        lista.add(this.telefono);
        lista.add(this.correo);
        lista.add(this.direccion);
        lista.add(this.tipoUsuario);
        lista.add(this.user);
        lista.add(this.pass);
        lista.add(this.estado);
        
        return lista;
    }
     
    public Usuario() {
    }

	
    public Usuario(String nombres, String apellidos, long telefono, String correo, String direccion, String tipoUsuario, String estado) {
        this.nombres = nombres;
        this.apellidos = apellidos;
        this.telefono = telefono;
        this.correo = correo;
        this.direccion = direccion;
        this.tipoUsuario = tipoUsuario;
        this.estado = estado;
    }
    public Usuario(String nombres, String apellidos, long telefono, String correo, String direccion, String tipoUsuario, String user, String pass, String estado, Set seguimientoses, Set contratoses) {
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.telefono = telefono;
       this.correo = correo;
       this.direccion = direccion;
       this.tipoUsuario = tipoUsuario;
       this.user = user;
       this.pass = pass;
       this.estado = estado;
       this.seguimientoses = seguimientoses;
       this.contratoses = contratoses;
    }

    public Usuario( String nombres, String apellidos, long telefono, String correo, String direccion, String tipoUsuario, String user, String pass, String estado) {
        
        this.nombres = nombres;
        this.apellidos = apellidos;
        this.telefono = telefono;
        this.correo = correo;
        this.direccion = direccion;
        this.tipoUsuario = tipoUsuario;
        this.user = user;
        this.pass = pass;
        this.estado = estado;
    }

    public Usuario(Integer idUsuarios, String nombres, String apellidos, long telefono, String correo, String direccion, String tipoUsuario) {
        this.idUsuarios = idUsuarios;
        this.nombres = nombres;
        this.apellidos = apellidos;
        this.telefono = telefono;
        this.correo = correo;
        this.direccion = direccion;
        this.tipoUsuario = tipoUsuario;
    }

    public Usuario(Integer idUsuarios) {
        this.idUsuarios = idUsuarios;
    }

    
   
    
    
    public Integer getIdUsuarios() {
        return this.idUsuarios;
    }
    
    public void setIdUsuarios(Integer idUsuarios) {
        this.idUsuarios = idUsuarios;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public long getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(long telefono) {
        this.telefono = telefono;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTipoUsuario() {
        return this.tipoUsuario;
    }
    
    public void setTipoUsuario(String tipoUsuario) {
        this.tipoUsuario = tipoUsuario;
    }
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getSeguimientoses() {
        return this.seguimientoses;
    }
    
    public void setSeguimientoses(Set seguimientoses) {
        this.seguimientoses = seguimientoses;
    }
    public Set getContratoses() {
        return this.contratoses;
    }
    
    public void setContratoses(Set contratoses) {
        this.contratoses = contratoses;
    }




}


